### PR TITLE
fix bug where helmit crashes

### PR DESCRIPTION
**Pull request by wilsonodk**
Only add pods to status that are in phase Running.

This will hopefully solve issue #14

### CODE REVIEW

**Comment by jkurz** [comment]
what about phases other than Pending? If we have never done this in the past, this may cause some confusion when things are being terminated, but not yet terminated. Or other use cases which are not Running.

This only shows logs when things are going good. I think this might cause more issues, by filtering this way.

**Comment by jkurz** [comment]
Also you say this hopefully fixes the issue. Does it fix it or not? I don't think this problem should be

**Comment by wilsonodk** [comment]
The problem is that the data model is changing in a way that is unexpected. For example, when it's being "Terminated", the logs are being shut off anyways, so removing them is the expected behavior. Also, when it's "Pending" and the logs haven't started.

Basically, this is going back to how it was when we had a synchronous deploy versus the asynchronous deployments that we now have.

**Comment by wilsonodk** [comment]
I should have provided more context; I made a lot of assumptions in my very limited description. I was very deep in the code and made the unfortunate assumption that everyone who would review this would understand all the issues I did.

The reason I say "hopefully" is that I think there will likely be some more fixes that will be needed to fully resolve the differences in the model from the four different states. We previously only cared about two states (running and error), but now (terminated and pending) are concerns. 

It's tough for me to model those, but over the next few days I'm going to get models for those states so that we can write tests around them. Then the hopefully will go aways. 

I know that this change resolves the issue I put in for issue #14, but there could be other crashes that are similar to #14 that this does not resolve.

**Pull request merged**
